Update docker image for Tez UI scripts
aws-samples/emr-serverless-samples pull request #10
Opened 2022-06-15 12:13 UTC by guptashailesh92

*Issue #, if available:*

Update Docker image files to formulate the log links correctly.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-06-20 20:45 UTC, dacort requested changes
This is really cool - love the devex improvement! A couple minor nits, but otherwise good to merge in when those are addressed. :)

2022-06-20 20:45 UTC, dacort commented on utilities/tez-ui/Dockerfile
> +RUN yum install -y patch
This could get moved to line 9 where we're already running `yum install`

2022-06-20 20:45 UTC, dacort commented on utilities/tez-ui/README.md
> +SERVERLESS_EMR_S3_LOG_BUCKET=$S3_BUCKET
Seems redundant to set this variable here when it's just being set to `$S3_BUCKET`.

2022-06-21 05:04 UTC, guptashailesh92 commented
Thanks. Updated with review comments.

2022-06-21 05:04 UTC, merged